export const LOAD_POKEMON = "LOAD_POKEMON";
export const LOAD_POKEMON_SUCCESS = "LOAD_POKEMON_SUCCESS";
export const LOAD_POKEMON_FAILURE = "LOAD_POKEMON_FAILURE";

export const LOAD_POKEMON_BY_TYPE = "LOAD_POKEMON_BY_TYPE";
export const LOAD_POKEMON_BY_TYPE_SUCCESS = "LOAD_POKEMON_BY_TYPE_SUCCESS";
export const LOAD_POKEMON_BY_TYPE_FAILURE = "LOAD_POKEMON_BY_TYPE_FAILURE";

export const LOAD_LIST_TYPE = "LOAD_LIST_TYPE";
export const LOAD_LIST_TYPE_SUCCESS = "LOAD_LIST_TYPE_SUCCESS";
export const LOAD_LIST_TYPE_FAILURE = "LOAD_LIST_TYPE_FAILURE";

export const RESET_POKEMON_LIST = "RESET_POKEMON_LIST";

export const LOAD_DETAIL_SUCCESS = "LOAD_DETAIL_SUCCESS";
export const LOAD_DETAIL_FAILURE = "LOAD_DETAIL_FAILURE";

export const RELEASE_MYPOKE_SUCCESS = "RELEASE_MYPOKE_SUCCESS";

export const CATCH_POKEMON_SUCCESS = "CATCH_POKEMON_SUCCESS";
export const CATCH_POKEMON_FAILURE = "CATCH_POKEMON_FAILURE";

export const BASE_URL = "https://pokeapi.co/api/v2/";
export const IMAGE_BASE_URL =
  "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/";
export const LIMIT = 24;
export const PROBABILITY = 0.5;
